//
// Created by diego on 27/11/2019.
//

#include "minunit.h"
#include <stdlib.h>
#include <stdio.h>
#include "Funciones.h"

#define MINUNIT_EPSILON 1E-12

char *html = {"<table class=\"ps_grid-flex\"><thead class=\"ps_grid-head\"><tr class=\"ps_grid-head-row\">\n"
              "<th scope=\"col\" class=\"ps_grid-col psc_sort-enabled\"><div class=\"ps_box_grid-col\"><a onclick=\"gKeyDownTarget = this; javascript:cancelBubble(event);\" href=\"javascript:submitAction_win15(document.win15,'CRSE_HIST2$srt10$0');\" title=\"Pulse para ordenar.\" class=\"ps_grid-col-label psc_link\" id=\"win15divDERIVED_SSS_HST_SSS_SUBJ_CATLG$80$lblhdr$0\">Clase</a></div></th><th scope=\"col\" class=\"ps_grid-col psc_sort-enabled\"><div class=\"ps_box_grid-col\"><a onclick=\"gKeyDownTarget = this; javascript:cancelBubble(event);\" href=\"javascript:submitAction_win15(document.win15,'CRSE_HIST2$srt12$0');\" title=\"Pulse para ordenar.\" class=\"ps_grid-col-label psc_link\" id=\"win15divDERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$lblhdr$0\">Descripción</a></div></th><th scope=\"col\" class=\"ps_grid-col CRSE_TERM3 psc_sort-enabled\"><div class=\"ps_box_grid-col\"><a onclick=\"gKeyDownTarget = this; javascript:cancelBubble(event);\" href=\"javascript:submitAction_win15(document.win15,'CRSE_HIST2$srt14$0');\" title=\"Pulse para ordenar.\" class=\"ps_grid-col-label psc_link\" id=\"win15divCRSE_TERM3lblhdr$0\">Ciclo</a></div></th><th scope=\"col\" class=\"ps_grid-col psc_sort-enabled\"><div class=\"ps_box_grid-col\"><a onclick=\"gKeyDownTarget = this; javascript:cancelBubble(event);\" href=\"javascript:submitAction_win15(document.win15,'CRSE_HIST2$srt16$0');\" title=\"Pulse para ordenar.\" class=\"ps_grid-col-label psc_link\" id=\"win15divDERIVED_SSS_HST_CRSE_GRADE_OFFlblhdr$0\">Calif</a></div></th><th scope=\"col\" class=\"ps_grid-col psc_num psc_sort-enabled\"><div class=\"ps_box_grid-col\"><a onclick=\"gKeyDownTarget = this; javascript:cancelBubble(event);\" href=\"javascript:submitAction_win15(document.win15,'CRSE_HIST2$srt17$0');\" title=\"Pulse para ordenar.\" class=\"ps_grid-col-label psc_link\" id=\"win15divDERIVED_SSS_HST_UNT_TAKENlblhdr$0\">Unidades</a></div></th><th scope=\"col\" class=\"ps_grid-col psc_sort-enabled\"><div class=\"ps_box_grid-col\"><a onclick=\"gKeyDownTarget = this; javascript:cancelBubble(event);\" href=\"javascript:submitAction_win15(document.win15,'CRSE_HIST2$srt18$0');\" title=\"Pulse para ordenar.\" class=\"ps_grid-col-label psc_link\" id=\"win15divDERIVED_SSS_HST_SSR_STATUS_LONGlblhdr$0\">Estado</a></div></th></tr></thead>\n"
              "<tbody class=\"ps_grid-body\"><tr class=\"ps_grid-row\" id=\"CRSE_HIST2$0_row_0\">\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psa_bold-anchor  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$0\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$0\">ET ET218</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$0\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$0\">Matrimonio: Sacramento de Amor</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell CRSE_TERM3\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_icon psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divCRSE_TERM3$0\"><span class=\"ps_box-value\" id=\"CRSE_TERM3$0\">Enero de 2020</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_CRSE_GRADE_OFF$0\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_CRSE_GRADE_OFF$0\">&nbsp;</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell psc_num\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_num  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_UNT_TAKEN$0\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_UNT_TAKEN$0\">2,00</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-htmlarea psc_label-suppressed\" id=\"win15divDERIVED_SSS_HST_SSR_STATUS_LONG$0\"><div class=\"ps-htmlarea\">\n"
              "<!-- Begin HTML Area Name Undisclosed -->\n"
              "<div class=\"ps_box-img psc_label-suppressed psc_display-inline psc_padding-right0_5em\"><img class=\"ps-img\" src=\"/cs/cs92pro/cache/PS_COURSE_PROGRESS_S_FL_ESP_1.svg\" alt=\"En Curso\" title=\"En Curso\"></div><div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_display-inline\"><span class=\"ps-box-value\" aria-disabled=\"true\">En Curso</span></div>\n"
              "<!-- End HTML Area -->\n"
              "</div>\n"
              "</div></td>\n"
              "</tr>\n"
              "<tr class=\"ps_grid-row\" id=\"CRSE_HIST2$0_row_1\">\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psa_bold-anchor  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$1\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$1\">FIS 1FIS211</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$1\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$1\">Lab. FIS-211</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell CRSE_TERM3\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_icon psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divCRSE_TERM3$1\"><span class=\"ps_box-value\" id=\"CRSE_TERM3$1\">Enero de 2020</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_CRSE_GRADE_OFF$1\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_CRSE_GRADE_OFF$1\">&nbsp;</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell psc_num\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_num  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_UNT_TAKEN$1\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_UNT_TAKEN$1\">1,00</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-htmlarea psc_label-suppressed\" id=\"win15divDERIVED_SSS_HST_SSR_STATUS_LONG$1\"><div class=\"ps-htmlarea\">\n"
              "<!-- Begin HTML Area Name Undisclosed -->\n"
              "<div class=\"ps_box-img psc_label-suppressed psc_display-inline psc_padding-right0_5em\"><img class=\"ps-img\" src=\"/cs/cs92pro/cache/PS_COURSE_PROGRESS_S_FL_ESP_1.svg\" alt=\"En Curso\" title=\"En Curso\"></div><div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_display-inline\"><span class=\"ps-box-value\" aria-disabled=\"true\">En Curso</span></div>\n"
              "<!-- End HTML Area -->\n"
              "</div>\n"
              "</div></td>\n"
              "</tr>\n"
              "<tr class=\"ps_grid-row\" id=\"CRSE_HIST2$0_row_2\">\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psa_bold-anchor  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$2\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$2\">FIS FIS211</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$2\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$2\">Física General I</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell CRSE_TERM3\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_icon psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divCRSE_TERM3$2\"><span class=\"ps_box-value\" id=\"CRSE_TERM3$2\">Enero de 2020</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_CRSE_GRADE_OFF$2\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_CRSE_GRADE_OFF$2\">&nbsp;</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell psc_num\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_num  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_UNT_TAKEN$2\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_UNT_TAKEN$2\">4,00</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-htmlarea psc_label-suppressed\" id=\"win15divDERIVED_SSS_HST_SSR_STATUS_LONG$2\"><div class=\"ps-htmlarea\">\n"
              "<!-- Begin HTML Area Name Undisclosed -->\n"
              "<div class=\"ps_box-img psc_label-suppressed psc_display-inline psc_padding-right0_5em\"><img class=\"ps-img\" src=\"/cs/cs92pro/cache/PS_COURSE_PROGRESS_S_FL_ESP_1.svg\" alt=\"En Curso\" title=\"En Curso\"></div><div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_display-inline\"><span class=\"ps-box-value\" aria-disabled=\"true\">En Curso</span></div>\n"
              "<!-- End HTML Area -->\n"
              "</div>\n"
              "</div></td>\n"
              "</tr>\n"
              "<tr class=\"ps_grid-row\" id=\"CRSE_HIST2$0_row_3\">\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psa_bold-anchor  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$3\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$3\">ILE ILE305</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$3\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$3\">Inglés III</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell CRSE_TERM3\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_icon psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divCRSE_TERM3$3\"><span class=\"ps_box-value\" id=\"CRSE_TERM3$3\">Enero de 2020</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_CRSE_GRADE_OFF$3\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_CRSE_GRADE_OFF$3\">&nbsp;</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell psc_num\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_num  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_UNT_TAKEN$3\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_UNT_TAKEN$3\">4,00</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-htmlarea psc_label-suppressed\" id=\"win15divDERIVED_SSS_HST_SSR_STATUS_LONG$3\"><div class=\"ps-htmlarea\">\n"
              "<!-- Begin HTML Area Name Undisclosed -->\n"
              "<div class=\"ps_box-img psc_label-suppressed psc_display-inline psc_padding-right0_5em\"><img class=\"ps-img\" src=\"/cs/cs92pro/cache/PS_COURSE_PROGRESS_S_FL_ESP_1.svg\" alt=\"En Curso\" title=\"En Curso\"></div><div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_display-inline\"><span class=\"ps-box-value\" aria-disabled=\"true\">En Curso</span></div>\n"
              "<!-- End HTML Area -->\n"
              "</div>\n"
              "</div></td>\n"
              "</tr>\n"
              "<tr class=\"ps_grid-row\" id=\"CRSE_HIST2$0_row_4\">\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psa_bold-anchor  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$4\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$4\">ISC ISC212</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$4\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$4\">Programación I</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell CRSE_TERM3\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_icon psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divCRSE_TERM3$4\"><span class=\"ps_box-value\" id=\"CRSE_TERM3$4\">Enero de 2020</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_CRSE_GRADE_OFF$4\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_CRSE_GRADE_OFF$4\">&nbsp;</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell psc_num\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_num  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_UNT_TAKEN$4\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_UNT_TAKEN$4\">4,00</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-htmlarea psc_label-suppressed\" id=\"win15divDERIVED_SSS_HST_SSR_STATUS_LONG$4\"><div class=\"ps-htmlarea\">\n"
              "<!-- Begin HTML Area Name Undisclosed -->\n"
              "<div class=\"ps_box-img psc_label-suppressed psc_display-inline psc_padding-right0_5em\"><img class=\"ps-img\" src=\"/cs/cs92pro/cache/PS_COURSE_PROGRESS_S_FL_ESP_1.svg\" alt=\"En Curso\" title=\"En Curso\"></div><div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_display-inline\"><span class=\"ps-box-value\" aria-disabled=\"true\">En Curso</span></div>\n"
              "<!-- End HTML Area -->\n"
              "</div>\n"
              "</div></td>\n"
              "</tr>\n"
              "<tr class=\"ps_grid-row\" id=\"CRSE_HIST2$0_row_5\">\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psa_bold-anchor  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$5\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$5\">MAT MAT212</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$5\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$5\">Cálculo II</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell CRSE_TERM3\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_icon psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divCRSE_TERM3$5\"><span class=\"ps_box-value\" id=\"CRSE_TERM3$5\">Enero de 2020</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_CRSE_GRADE_OFF$5\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_CRSE_GRADE_OFF$5\">&nbsp;</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell psc_num\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_num  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_UNT_TAKEN$5\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_UNT_TAKEN$5\">5,00</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-htmlarea psc_label-suppressed\" id=\"win15divDERIVED_SSS_HST_SSR_STATUS_LONG$5\"><div class=\"ps-htmlarea\">\n"
              "<!-- Begin HTML Area Name Undisclosed -->\n"
              "<div class=\"ps_box-img psc_label-suppressed psc_display-inline psc_padding-right0_5em\"><img class=\"ps-img\" src=\"/cs/cs92pro/cache/PS_COURSE_PROGRESS_S_FL_ESP_1.svg\" alt=\"En Curso\" title=\"En Curso\"></div><div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_display-inline\"><span class=\"ps-box-value\" aria-disabled=\"true\">En Curso</span></div>\n"
              "<!-- End HTML Area -->\n"
              "</div>\n"
              "</div></td>\n"
              "</tr>\n"
              "<tr class=\"ps_grid-row\" id=\"CRSE_HIST2$0_row_6\">\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psa_bold-anchor  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$6\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$6\">FIL FIL121</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$6\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$6\">Introducción a la Filosofía</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell CRSE_TERM3\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_icon psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divCRSE_TERM3$6\"><span class=\"ps_box-value\" id=\"CRSE_TERM3$6\">Septiembre de 2019</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_CRSE_GRADE_OFF$6\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_CRSE_GRADE_OFF$6\">&nbsp;</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell psc_num\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_num  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_UNT_TAKEN$6\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_UNT_TAKEN$6\">3,00</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-htmlarea psc_label-suppressed\" id=\"win15divDERIVED_SSS_HST_SSR_STATUS_LONG$6\"><div class=\"ps-htmlarea\">\n"
              "<!-- Begin HTML Area Name Undisclosed -->\n"
              "<div class=\"ps_box-img psc_label-suppressed psc_display-inline psc_padding-right0_5em\"><img class=\"ps-img\" src=\"/cs/cs92pro/cache/PS_COURSE_PROGRESS_S_FL_ESP_1.svg\" alt=\"En Curso\" title=\"En Curso\"></div><div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_display-inline\"><span class=\"ps-box-value\" aria-disabled=\"true\">En Curso</span></div>\n"
              "<!-- End HTML Area -->\n"
              "</div>\n"
              "</div></td>\n"
              "</tr>\n"
              "<tr class=\"ps_grid-row\" id=\"CRSE_HIST2$0_row_7\">\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psa_bold-anchor  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$7\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$7\">ILE ILE303</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$7\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$7\">Inglés II</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell CRSE_TERM3\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_icon psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divCRSE_TERM3$7\"><span class=\"ps_box-value\" id=\"CRSE_TERM3$7\">Septiembre de 2019</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_CRSE_GRADE_OFF$7\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_CRSE_GRADE_OFF$7\">&nbsp;</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell psc_num\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_num  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_UNT_TAKEN$7\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_UNT_TAKEN$7\">4,00</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-htmlarea psc_label-suppressed\" id=\"win15divDERIVED_SSS_HST_SSR_STATUS_LONG$7\"><div class=\"ps-htmlarea\">\n"
              "<!-- Begin HTML Area Name Undisclosed -->\n"
              "<div class=\"ps_box-img psc_label-suppressed psc_display-inline psc_padding-right0_5em\"><img class=\"ps-img\" src=\"/cs/cs92pro/cache/PS_COURSE_PROGRESS_S_FL_ESP_1.svg\" alt=\"En Curso\" title=\"En Curso\"></div><div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_display-inline\"><span class=\"ps-box-value\" aria-disabled=\"true\">En Curso</span></div>\n"
              "<!-- End HTML Area -->\n"
              "</div>\n"
              "</div></td>\n"
              "</tr>\n"
              "<tr class=\"ps_grid-row\" id=\"CRSE_HIST2$0_row_8\">\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psa_bold-anchor  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$8\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$8\">ISC ISC105</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$8\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$8\">Fundamentos de Programación</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell CRSE_TERM3\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_icon psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divCRSE_TERM3$8\"><span class=\"ps_box-value\" id=\"CRSE_TERM3$8\">Septiembre de 2019</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_CRSE_GRADE_OFF$8\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_CRSE_GRADE_OFF$8\">&nbsp;</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell psc_num\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_num  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_UNT_TAKEN$8\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_UNT_TAKEN$8\">4,00</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-htmlarea psc_label-suppressed\" id=\"win15divDERIVED_SSS_HST_SSR_STATUS_LONG$8\"><div class=\"ps-htmlarea\">\n"
              "<!-- Begin HTML Area Name Undisclosed -->\n"
              "<div class=\"ps_box-img psc_label-suppressed psc_display-inline psc_padding-right0_5em\"><img class=\"ps-img\" src=\"/cs/cs92pro/cache/PS_COURSE_PROGRESS_S_FL_ESP_1.svg\" alt=\"En Curso\" title=\"En Curso\"></div><div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_display-inline\"><span class=\"ps-box-value\" aria-disabled=\"true\">En Curso</span></div>\n"
              "<!-- End HTML Area -->\n"
              "</div>\n"
              "</div></td>\n"
              "</tr>\n"
              "<tr class=\"ps_grid-row\" id=\"CRSE_HIST2$0_row_9\">\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psa_bold-anchor  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$9\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$9\">MAT MAT211</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$9\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$9\">Cálculo I</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell CRSE_TERM3\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_icon psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divCRSE_TERM3$9\"><span class=\"ps_box-value\" id=\"CRSE_TERM3$9\">Septiembre de 2019</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_CRSE_GRADE_OFF$9\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_CRSE_GRADE_OFF$9\">&nbsp;</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell psc_num\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_num  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_UNT_TAKEN$9\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_UNT_TAKEN$9\">5,00</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-htmlarea psc_label-suppressed\" id=\"win15divDERIVED_SSS_HST_SSR_STATUS_LONG$9\"><div class=\"ps-htmlarea\">\n"
              "<!-- Begin HTML Area Name Undisclosed -->\n"
              "<div class=\"ps_box-img psc_label-suppressed psc_display-inline psc_padding-right0_5em\"><img class=\"ps-img\" src=\"/cs/cs92pro/cache/PS_COURSE_PROGRESS_S_FL_ESP_1.svg\" alt=\"En Curso\" title=\"En Curso\"></div><div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_display-inline\"><span class=\"ps-box-value\" aria-disabled=\"true\">En Curso</span></div>\n"
              "<!-- End HTML Area -->\n"
              "</div>\n"
              "</div></td>\n"
              "</tr>\n"
              "<tr class=\"ps_grid-row\" id=\"CRSE_HIST2$0_row_10\">\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psa_bold-anchor  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$10\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$10\">FIS 1FIS101</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$10\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$10\">Lab. FIS-101</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell CRSE_TERM3\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_icon psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divCRSE_TERM3$10\"><span class=\"ps_box-value\" id=\"CRSE_TERM3$10\">Abril de 2019</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_CRSE_GRADE_OFF$10\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_CRSE_GRADE_OFF$10\">B</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell psc_num\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_num  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_UNT_TAKEN$10\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_UNT_TAKEN$10\">1,00</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-htmlarea psc_label-suppressed\" id=\"win15divDERIVED_SSS_HST_SSR_STATUS_LONG$10\"><div class=\"ps-htmlarea\">\n"
              "<!-- Begin HTML Area Name Undisclosed -->\n"
              "<div class=\"ps_box-img psc_label-suppressed psc_display-inline psc_padding-right0_5em\"><img class=\"ps-img\" src=\"/cs/cs92pro/cache/PS_SUCCESS_S_FL_ESP_1.svg\" alt=\"Realizado\" title=\"Realizado\"></div><div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_display-inline\"><span class=\"ps-box-value\" aria-disabled=\"true\">Realizado</span></div>\n"
              "<!-- End HTML Area -->\n"
              "</div>\n"
              "</div></td>\n"
              "</tr>\n"
              "<tr class=\"ps_grid-row\" id=\"CRSE_HIST2$0_row_11\">\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psa_bold-anchor  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$11\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$11\">FIS FIS101</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$11\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$11\">Introducción a la Física</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell CRSE_TERM3\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_icon psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divCRSE_TERM3$11\"><span class=\"ps_box-value\" id=\"CRSE_TERM3$11\">Abril de 2019</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_CRSE_GRADE_OFF$11\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_CRSE_GRADE_OFF$11\">B</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell psc_num\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_num  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_UNT_TAKEN$11\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_UNT_TAKEN$11\">5,00</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-htmlarea psc_label-suppressed\" id=\"win15divDERIVED_SSS_HST_SSR_STATUS_LONG$11\"><div class=\"ps-htmlarea\">\n"
              "<!-- Begin HTML Area Name Undisclosed -->\n"
              "<div class=\"ps_box-img psc_label-suppressed psc_display-inline psc_padding-right0_5em\"><img class=\"ps-img\" src=\"/cs/cs92pro/cache/PS_SUCCESS_S_FL_ESP_1.svg\" alt=\"Realizado\" title=\"Realizado\"></div><div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_display-inline\"><span class=\"ps-box-value\" aria-disabled=\"true\">Realizado</span></div>\n"
              "<!-- End HTML Area -->\n"
              "</div>\n"
              "</div></td>\n"
              "</tr>\n"
              "<tr class=\"ps_grid-row\" id=\"CRSE_HIST2$0_row_12\">\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psa_bold-anchor  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$12\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$12\">HG HG103</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$12\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$12\">Introducción Historia Dominica</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell CRSE_TERM3\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_icon psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divCRSE_TERM3$12\"><span class=\"ps_box-value\" id=\"CRSE_TERM3$12\">Abril de 2019</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_CRSE_GRADE_OFF$12\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_CRSE_GRADE_OFF$12\">A</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell psc_num\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_num  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_UNT_TAKEN$12\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_UNT_TAKEN$12\">3,00</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-htmlarea psc_label-suppressed\" id=\"win15divDERIVED_SSS_HST_SSR_STATUS_LONG$12\"><div class=\"ps-htmlarea\">\n"
              "<!-- Begin HTML Area Name Undisclosed -->\n"
              "<div class=\"ps_box-img psc_label-suppressed psc_display-inline psc_padding-right0_5em\"><img class=\"ps-img\" src=\"/cs/cs92pro/cache/PS_SUCCESS_S_FL_ESP_1.svg\" alt=\"Realizado\" title=\"Realizado\"></div><div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_display-inline\"><span class=\"ps-box-value\" aria-disabled=\"true\">Realizado</span></div>\n"
              "<!-- End HTML Area -->\n"
              "</div>\n"
              "</div></td>\n"
              "</tr>\n"
              "<tr class=\"ps_grid-row\" id=\"CRSE_HIST2$0_row_13\">\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psa_bold-anchor  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$13\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$13\">ILE ILE205</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$13\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$13\">Inglés I</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell CRSE_TERM3\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_icon psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divCRSE_TERM3$13\"><span class=\"ps_box-value\" id=\"CRSE_TERM3$13\">Abril de 2019</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_CRSE_GRADE_OFF$13\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_CRSE_GRADE_OFF$13\">B</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell psc_num\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_num  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_UNT_TAKEN$13\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_UNT_TAKEN$13\">4,00</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-htmlarea psc_label-suppressed\" id=\"win15divDERIVED_SSS_HST_SSR_STATUS_LONG$13\"><div class=\"ps-htmlarea\">\n"
              "<!-- Begin HTML Area Name Undisclosed -->\n"
              "<div class=\"ps_box-img psc_label-suppressed psc_display-inline psc_padding-right0_5em\"><img class=\"ps-img\" src=\"/cs/cs92pro/cache/PS_SUCCESS_S_FL_ESP_1.svg\" alt=\"Realizado\" title=\"Realizado\"></div><div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_display-inline\"><span class=\"ps-box-value\" aria-disabled=\"true\">Realizado</span></div>\n"
              "<!-- End HTML Area -->\n"
              "</div>\n"
              "</div></td>\n"
              "</tr>\n"
              "<tr class=\"ps_grid-row\" id=\"CRSE_HIST2$0_row_14\">\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psa_bold-anchor  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$14\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$14\">ISC ISC104</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$14\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$14\">Introducción a la Algoritmia</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell CRSE_TERM3\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_icon psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divCRSE_TERM3$14\"><span class=\"ps_box-value\" id=\"CRSE_TERM3$14\">Abril de 2019</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_CRSE_GRADE_OFF$14\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_CRSE_GRADE_OFF$14\">B</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell psc_num\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_num  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_UNT_TAKEN$14\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_UNT_TAKEN$14\">3,00</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-htmlarea psc_label-suppressed\" id=\"win15divDERIVED_SSS_HST_SSR_STATUS_LONG$14\"><div class=\"ps-htmlarea\">\n"
              "<!-- Begin HTML Area Name Undisclosed -->\n"
              "<div class=\"ps_box-img psc_label-suppressed psc_display-inline psc_padding-right0_5em\"><img class=\"ps-img\" src=\"/cs/cs92pro/cache/PS_SUCCESS_S_FL_ESP_1.svg\" alt=\"Realizado\" title=\"Realizado\"></div><div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_display-inline\"><span class=\"ps-box-value\" aria-disabled=\"true\">Realizado</span></div>\n"
              "<!-- End HTML Area -->\n"
              "</div>\n"
              "</div></td>\n"
              "</tr>\n"
              "<tr class=\"ps_grid-row\" id=\"CRSE_HIST2$0_row_15\">\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psa_bold-anchor  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$15\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$15\">LET LET102</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$15\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$15\">Español II</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell CRSE_TERM3\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_icon psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divCRSE_TERM3$15\"><span class=\"ps_box-value\" id=\"CRSE_TERM3$15\">Abril de 2019</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_CRSE_GRADE_OFF$15\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_CRSE_GRADE_OFF$15\">A</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell psc_num\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_num  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_UNT_TAKEN$15\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_UNT_TAKEN$15\">4,00</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-htmlarea psc_label-suppressed\" id=\"win15divDERIVED_SSS_HST_SSR_STATUS_LONG$15\"><div class=\"ps-htmlarea\">\n"
              "<!-- Begin HTML Area Name Undisclosed -->\n"
              "<div class=\"ps_box-img psc_label-suppressed psc_display-inline psc_padding-right0_5em\"><img class=\"ps-img\" src=\"/cs/cs92pro/cache/PS_SUCCESS_S_FL_ESP_1.svg\" alt=\"Realizado\" title=\"Realizado\"></div><div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_display-inline\"><span class=\"ps-box-value\" aria-disabled=\"true\">Realizado</span></div>\n"
              "<!-- End HTML Area -->\n"
              "</div>\n"
              "</div></td>\n"
              "</tr>\n"
              "<tr class=\"ps_grid-row\" id=\"CRSE_HIST2$0_row_16\">\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psa_bold-anchor  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$16\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$16\">MAT MAT102</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$16\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$16\">Matemática Universitaria II-B</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell CRSE_TERM3\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_icon psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divCRSE_TERM3$16\"><span class=\"ps_box-value\" id=\"CRSE_TERM3$16\">Abril de 2019</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_CRSE_GRADE_OFF$16\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_CRSE_GRADE_OFF$16\">A</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell psc_num\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_num  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_UNT_TAKEN$16\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_UNT_TAKEN$16\">5,00</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-htmlarea psc_label-suppressed\" id=\"win15divDERIVED_SSS_HST_SSR_STATUS_LONG$16\"><div class=\"ps-htmlarea\">\n"
              "<!-- Begin HTML Area Name Undisclosed -->\n"
              "<div class=\"ps_box-img psc_label-suppressed psc_display-inline psc_padding-right0_5em\"><img class=\"ps-img\" src=\"/cs/cs92pro/cache/PS_SUCCESS_S_FL_ESP_1.svg\" alt=\"Realizado\" title=\"Realizado\"></div><div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_display-inline\"><span class=\"ps-box-value\" aria-disabled=\"true\">Realizado</span></div>\n"
              "<!-- End HTML Area -->\n"
              "</div>\n"
              "</div></td>\n"
              "</tr>\n"
              "<tr class=\"ps_grid-row\" id=\"CRSE_HIST2$0_row_17\">\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psa_bold-anchor  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$17\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$17\">DEP 1DEP102</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$17\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$17\">Fútbol</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell CRSE_TERM3\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_icon psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divCRSE_TERM3$17\"><span class=\"ps_box-value\" id=\"CRSE_TERM3$17\">Enero de 2019</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_CRSE_GRADE_OFF$17\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_CRSE_GRADE_OFF$17\">A</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell psc_num\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_num  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_UNT_TAKEN$17\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_UNT_TAKEN$17\">1,00</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-htmlarea psc_label-suppressed\" id=\"win15divDERIVED_SSS_HST_SSR_STATUS_LONG$17\"><div class=\"ps-htmlarea\">\n"
              "<!-- Begin HTML Area Name Undisclosed -->\n"
              "<div class=\"ps_box-img psc_label-suppressed psc_display-inline psc_padding-right0_5em\"><img class=\"ps-img\" src=\"/cs/cs92pro/cache/PS_SUCCESS_S_FL_ESP_1.svg\" alt=\"Realizado\" title=\"Realizado\"></div><div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_display-inline\"><span class=\"ps-box-value\" aria-disabled=\"true\">Realizado</span></div>\n"
              "<!-- End HTML Area -->\n"
              "</div>\n"
              "</div></td>\n"
              "</tr>\n"
              "<tr class=\"ps_grid-row\" id=\"CRSE_HIST2$0_row_18\">\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psa_bold-anchor  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$18\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$18\">HG HG101</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$18\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$18\">Historia de la Cultura Occiden</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell CRSE_TERM3\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_icon psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divCRSE_TERM3$18\"><span class=\"ps_box-value\" id=\"CRSE_TERM3$18\">Enero de 2019</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_CRSE_GRADE_OFF$18\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_CRSE_GRADE_OFF$18\">A</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell psc_num\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_num  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_UNT_TAKEN$18\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_UNT_TAKEN$18\">3,00</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-htmlarea psc_label-suppressed\" id=\"win15divDERIVED_SSS_HST_SSR_STATUS_LONG$18\"><div class=\"ps-htmlarea\">\n"
              "<!-- Begin HTML Area Name Undisclosed -->\n"
              "<div class=\"ps_box-img psc_label-suppressed psc_display-inline psc_padding-right0_5em\"><img class=\"ps-img\" src=\"/cs/cs92pro/cache/PS_SUCCESS_S_FL_ESP_1.svg\" alt=\"Realizado\" title=\"Realizado\"></div><div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_display-inline\"><span class=\"ps-box-value\" aria-disabled=\"true\">Realizado</span></div>\n"
              "<!-- End HTML Area -->\n"
              "</div>\n"
              "</div></td>\n"
              "</tr>\n"
              "<tr class=\"ps_grid-row\" id=\"CRSE_HIST2$0_row_19\">\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psa_bold-anchor  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$19\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$19\">ILE ILE103</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$19\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$19\">Inglés Básico I</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell CRSE_TERM3\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_icon psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divCRSE_TERM3$19\"><span class=\"ps_box-value\" id=\"CRSE_TERM3$19\">Enero de 2019</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_CRSE_GRADE_OFF$19\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_CRSE_GRADE_OFF$19\">EXO</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell psc_num\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_num  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_UNT_TAKEN$19\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_UNT_TAKEN$19\">&nbsp;</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-htmlarea psc_label-suppressed\" id=\"win15divDERIVED_SSS_HST_SSR_STATUS_LONG$19\"><div class=\"ps-htmlarea\">\n"
              "<!-- Begin HTML Area Name Undisclosed -->\n"
              "<div class=\"ps_box-img psc_label-suppressed psc_display-inline psc_padding-right0_5em\"><img class=\"ps-img\" src=\"/cs/cs92pro/cache/PS_COURSE_TRANS_S_FL_ESP_1.svg\" alt=\"Transferido\" title=\"Transferido\"></div><div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_display-inline\"><span class=\"ps-box-value\" aria-disabled=\"true\">Transferido</span></div>\n"
              "<!-- End HTML Area -->\n"
              "</div>\n"
              "</div></td>\n"
              "</tr>\n"
              "<tr class=\"ps_grid-row\" id=\"CRSE_HIST2$0_row_20\">\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psa_bold-anchor  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$20\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$20\">ILE ILE203</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$20\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$20\">Inglés Básico II</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell CRSE_TERM3\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_icon psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divCRSE_TERM3$20\"><span class=\"ps_box-value\" id=\"CRSE_TERM3$20\">Enero de 2019</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_CRSE_GRADE_OFF$20\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_CRSE_GRADE_OFF$20\">S</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell psc_num\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_num  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_UNT_TAKEN$20\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_UNT_TAKEN$20\">&nbsp;</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-htmlarea psc_label-suppressed\" id=\"win15divDERIVED_SSS_HST_SSR_STATUS_LONG$20\"><div class=\"ps-htmlarea\">\n"
              "<!-- Begin HTML Area Name Undisclosed -->\n"
              "<div class=\"ps_box-img psc_label-suppressed psc_display-inline psc_padding-right0_5em\"><img class=\"ps-img\" src=\"/cs/cs92pro/cache/PS_SUCCESS_S_FL_ESP_1.svg\" alt=\"Realizado\" title=\"Realizado\"></div><div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_display-inline\"><span class=\"ps-box-value\" aria-disabled=\"true\">Realizado</span></div>\n"
              "<!-- End HTML Area -->\n"
              "</div>\n"
              "</div></td>\n"
              "</tr>\n"
              "<tr class=\"ps_grid-row\" id=\"CRSE_HIST2$0_row_21\">\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psa_bold-anchor  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$21\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$21\">ISC ISC101</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$21\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$21\">Introd. a Sistemas Computacion</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell CRSE_TERM3\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_icon psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divCRSE_TERM3$21\"><span class=\"ps_box-value\" id=\"CRSE_TERM3$21\">Enero de 2019</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_CRSE_GRADE_OFF$21\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_CRSE_GRADE_OFF$21\">A</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell psc_num\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_num  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_UNT_TAKEN$21\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_UNT_TAKEN$21\">3,00</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-htmlarea psc_label-suppressed\" id=\"win15divDERIVED_SSS_HST_SSR_STATUS_LONG$21\"><div class=\"ps-htmlarea\">\n"
              "<!-- Begin HTML Area Name Undisclosed -->\n"
              "<div class=\"ps_box-img psc_label-suppressed psc_display-inline psc_padding-right0_5em\"><img class=\"ps-img\" src=\"/cs/cs92pro/cache/PS_SUCCESS_S_FL_ESP_1.svg\" alt=\"Realizado\" title=\"Realizado\"></div><div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_display-inline\"><span class=\"ps-box-value\" aria-disabled=\"true\">Realizado</span></div>\n"
              "<!-- End HTML Area -->\n"
              "</div>\n"
              "</div></td>\n"
              "</tr>\n"
              "<tr class=\"ps_grid-row\" id=\"CRSE_HIST2$0_row_22\">\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psa_bold-anchor  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$22\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$22\">LET LET101</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$22\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$22\">Español I</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell CRSE_TERM3\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_icon psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divCRSE_TERM3$22\"><span class=\"ps_box-value\" id=\"CRSE_TERM3$22\">Enero de 2019</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_CRSE_GRADE_OFF$22\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_CRSE_GRADE_OFF$22\">A</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell psc_num\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_num  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_UNT_TAKEN$22\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_UNT_TAKEN$22\">4,00</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-htmlarea psc_label-suppressed\" id=\"win15divDERIVED_SSS_HST_SSR_STATUS_LONG$22\"><div class=\"ps-htmlarea\">\n"
              "<!-- Begin HTML Area Name Undisclosed -->\n"
              "<div class=\"ps_box-img psc_label-suppressed psc_display-inline psc_padding-right0_5em\"><img class=\"ps-img\" src=\"/cs/cs92pro/cache/PS_SUCCESS_S_FL_ESP_1.svg\" alt=\"Realizado\" title=\"Realizado\"></div><div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_display-inline\"><span class=\"ps-box-value\" aria-disabled=\"true\">Realizado</span></div>\n"
              "<!-- End HTML Area -->\n"
              "</div>\n"
              "</div></td>\n"
              "</tr>\n"
              "<tr class=\"ps_grid-row\" id=\"CRSE_HIST2$0_row_23\">\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psa_bold-anchor  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$23\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$23\">MAT MAT101</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$23\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$23\">Matemática Universitaria I</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell CRSE_TERM3\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_icon psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divCRSE_TERM3$23\"><span class=\"ps_box-value\" id=\"CRSE_TERM3$23\">Enero de 2019</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_CRSE_GRADE_OFF$23\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_CRSE_GRADE_OFF$23\">A</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell psc_num\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_num  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_UNT_TAKEN$23\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_UNT_TAKEN$23\">5,00</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-htmlarea psc_label-suppressed\" id=\"win15divDERIVED_SSS_HST_SSR_STATUS_LONG$23\"><div class=\"ps-htmlarea\">\n"
              "<!-- Begin HTML Area Name Undisclosed -->\n"
              "<div class=\"ps_box-img psc_label-suppressed psc_display-inline psc_padding-right0_5em\"><img class=\"ps-img\" src=\"/cs/cs92pro/cache/PS_SUCCESS_S_FL_ESP_1.svg\" alt=\"Realizado\" title=\"Realizado\"></div><div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_display-inline\"><span class=\"ps-box-value\" aria-disabled=\"true\">Realizado</span></div>\n"
              "<!-- End HTML Area -->\n"
              "</div>\n"
              "</div></td>\n"
              "</tr>\n"
              "<tr class=\"ps_grid-row\" id=\"CRSE_HIST2$0_row_24\">\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psa_bold-anchor  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$24\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$24\">ORI ORI101</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$24\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$24\">Orientación Académica</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell CRSE_TERM3\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_icon psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divCRSE_TERM3$24\"><span class=\"ps_box-value\" id=\"CRSE_TERM3$24\">Enero de 2019</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_CRSE_GRADE_OFF$24\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_CRSE_GRADE_OFF$24\">A</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell psc_num\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_num  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_UNT_TAKEN$24\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_UNT_TAKEN$24\">1,00</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-htmlarea psc_label-suppressed\" id=\"win15divDERIVED_SSS_HST_SSR_STATUS_LONG$24\"><div class=\"ps-htmlarea\">\n"
              "<!-- Begin HTML Area Name Undisclosed -->\n"
              "<div class=\"ps_box-img psc_label-suppressed psc_display-inline psc_padding-right0_5em\"><img class=\"ps-img\" src=\"/cs/cs92pro/cache/PS_SUCCESS_S_FL_ESP_1.svg\" alt=\"Realizado\" title=\"Realizado\"></div><div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_display-inline\"><span class=\"ps-box-value\" aria-disabled=\"true\">Realizado</span></div>\n"
              "<!-- End HTML Area -->\n"
              "</div>\n"
              "</div></td>\n"
              "</tr>\n"
              "<tr class=\"ps_grid-row\" id=\"CRSE_HIST2$0_row_25\">\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psa_bold-anchor  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$25\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSS_SUBJ_CATLG$80$$25\">MAT MAT212</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$25\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_SSR_CLASSNAME_LONG$83$$25\">Cálculo II</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell CRSE_TERM3\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_icon psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divCRSE_TERM3$25\"><span class=\"ps_box-value\" id=\"CRSE_TERM3$25\">No Asignado</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_CRSE_GRADE_OFF$25\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_CRSE_GRADE_OFF$25\">&nbsp;</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell psc_num\">\n"
              "<div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_num  psc_label-hide\" id=\"win15divDERIVED_SSS_HST_UNT_TAKEN$25\"><span class=\"ps_box-value\" id=\"DERIVED_SSS_HST_UNT_TAKEN$25\">5,00</span>\n"
              "</div></td>\n"
              "<td class=\"ps_grid-cell\">\n"
              "<div class=\"ps_box-htmlarea psc_label-suppressed\" id=\"win15divDERIVED_SSS_HST_SSR_STATUS_LONG$25\"><div class=\"ps-htmlarea\">\n"
              "<!-- Begin HTML Area Name Undisclosed -->\n"
              "<div class=\"ps_box-img psc_label-suppressed psc_display-inline psc_padding-right0_5em\"><img class=\"ps-img\" src=\"/cs/cs92pro/cache/PS_COURSE_PLANNED_S_FL_ESP_1.svg\" alt=\"Planificado\" title=\"Planificado\"></div><div class=\"ps_box-edit psc_disabled psc_label-suppressed psc_has_value psc_display-inline\"><span class=\"ps-box-value\" aria-disabled=\"true\">Planificado</span></div>\n"
              "<!-- End HTML Area -->\n"
              "</div>\n"
              "</div></td>\n"
              "</tr>\n"
              "</tbody></table>"};

MU_TEST(NOTA) {
    char *p = html;
    char *a;

    a = nota(p);

    mu_assert_int_eq('A',*a);
}

MU_TEST(CREDITO) {
    char *p = html;
    char *a;

    a = credito(p);

    mu_assert_int_eq('3',*a);

}

MU_TEST(DISPONIBLE) {
    char *p = html;
    int a;

    a = disponibilidad(p);

    mu_assert_int_eq(1,a);

}

MU_TEST(MATERIA) {
    char *p = html;

    p = materia(p);

    mu_assert_int_eq('I',p[0]);
    mu_assert_int_eq('n',p[1]);
    mu_assert_int_eq('t',p[2]);
    mu_assert_int_eq('r',p[3]);
    mu_assert_int_eq('o',p[4]);
    mu_assert_int_eq('d',p[5]);
    mu_assert_int_eq('u',p[6]);
    mu_assert_int_eq('c',p[7]);
    mu_assert_int_eq('c',p[8]);
    mu_assert_int_eq('i',p[9]);
    mu_assert_int_eq('o',p[10]);
    mu_assert_int_eq('n',p[11]);
}

MU_TEST(INDICE) {
    char *p = html;

    printf("%.2f",indice(p));
}



MU_TEST_SUITE(test_suite) {
    MU_RUN_TEST(INDICE);
}

int main(int argc, char *argv[]) {
    MU_RUN_SUITE(test_suite);
    MU_REPORT();
    return 0;
}